### ISSUE TITLE
@context url is not valid

### ISSUE THREAD

**Issue by earlyster** [veres-one/did-veres-one#3]
I was trying to review the json ld for a generated did file and noticed that the @context url https://w3id.org/veres-one/v1 is redirecting to https://digitalbazaar.github.io/veres-one-context/contexts/veres-one-v1.jsonld which is giving a 404. I am not sure if this is correct url but I am learning about DID and was trying out the did-client from - https://github.com/digitalbazaar/did-client

**Comment by earlyster** [comment]
Found this page was pulled down - https://github.com/digitalbazaar/did-client/commit/887673288545919efefb19644f1ea7227efdb144

**Comment by davidlehn** [comment]
That w3id redir is wrong since the repo moved.  Should be https://veres-one.github.io/veres-one-context/contexts/veres-one-v1.jsonld.  I just fixed it.  did-client is now actually using a local context in this repo in `lib/contexts/`.  It can be a bit confusing that way but seems to be easier to have fast and easy to edit local contexts while developing.  Contexts will get synced up as needed.

**Comment by earlyster** [comment]
Works thanks for updating redirect!
